name: " Nightly "

on:
  push:
    paths:
      - 'patches/**'
  workflow_dispatch:
    inputs:
      commit:
        description: 'Specify commit (e.g. ecd01e13fd)'
        required: false
        default: 'ecd01e13fd'

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  pushed:
    if: ${{ github.event_name == 'push' }}
    name: Pushed Build
    concurrency:
      group: nightly-build
      cancel-in-progress: false
    uses: ./.github/workflows/buildnightly.yml
    with:
      build-id: 'pushed'
      build-commit: ${{ github.event.head_commit.message }}
    secrets: inherit

  manual:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    name: Manual Build
    concurrency:
      group: nightly-build
      cancel-in-progress: false
    uses: ./.github/workflows/buildnightly.yml
    with:
      build-id: 'manual'
      build-commit: ${{ github.event.inputs.commit }}
    secrets: inherit
