name: "[Auto] Tagged Release"

on:
  repository_dispatch:
    types: [tag]

env:
  DISABLE_ARM: ${{ vars.DISABLE_ARM }}

jobs:
  build:
    name: Build
    concurrency:
      group: tag-build
      cancel-in-progress: true
    uses: ./.github/workflows/build.yml
    with:
      devel: false
      build-id: 'tag'
    secrets: inherit

  release:
    name: "Create Release"
    needs: [build]
    permissions:
      actions: read
      security-events: write
      contents: write
      discussions: write
    uses: ./.github/workflows/release.yml
    with:
      devel: true
      build-id: 'tag'
      status: ${{ needs.build.status }}
    secrets: inherit